import { Yuji_Boku } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const yujiBokuSans = Yuji_Boku({
  weight: "400",
  variable: "--font-yuji-boku-sans",
  subsets: ["latin"],
});

const yujiBokuMono = Yuji_Boku({
  weight: "400",
  variable: "--font-yuji-boku-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${yujiBokuSans.variable} ${yujiBokuMono.variable} antialiased`}
      >
        <main className="app-root">
          {children}
        </main>
      </body>
    </html>
  );
}
