import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import DesktopLayout from "@/components/desktop/DesktopLayout";
import { WindowProvider } from "@/components/container/WindowsContext";

const robotoSans = Roboto_Mono({
  weight: "400",
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  weight: "400",
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${robotoSans.variable} antialiased`}
      >
        <main className="app-root">
          <DesktopLayout>
            <WindowProvider>
              <div className="app-content">
                {children}
              </div>
            </WindowProvider>
          </DesktopLayout>
        </main>
      </body>
    </html>
  );
}
